version: '3'
services:
  api:
    container_name: airbnb-api
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/airbnb
      - JWT_SECRET=airbnb
    depends_on:
      - mongo
  client:
    container_name: airbnb-client
    build: ./client
    ports:
      - 5173:5173
    volumes:
      - ./client:/usr/src/client
      - /usr/src/client/node_modules
  mongo:
    image: mongo
    ports:
      - 27017:27017